### ISSUE TITLE
No such image: frodenas/redis:2.8 (tag: 2.8)

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/docker-broker-images-boshrelease#4]
With both v1 and v2:

```
$ cf cs redis28 free r1
Creating service instance r1 in org system / space subway as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: #<Docker::Error::NotFoundError: No such image: frodenas/redis:2.8 (tag: 2.8)
```

**Comment by drnic** [comment]
```
# docker --host unix:///var/vcap/sys/run/docker/docker.sock images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
```

I guess I'm not setting up offline mode correctly yet.

**Comment by drnic** [comment]
OOh, you added an errand to install packages instead of loading them via job templates. Why? Or rather, can I introduce you to how I did the image installation in other releases?

https://github.com/cloudfoundry-community/logstash-docker-boshrelease/blob/master/jobs/cfcommunity_logstash_image/templates/bin/install_ctl#L20-L24

The job template is included into each docker job and it installs the package locally.

**Comment by drnic** [comment]
I don't like that we need docker to be listening on TCP - I'd prefer it was only communicated with locally via sockets https://github.com/cloudfoundry-community/docker-broker-images-boshrelease/blob/master/jobs/docker_load_images/templates/bin/run#L15

**Comment by rkoster** [comment]
Yhea looked at your method, but took the errand inspiration from the docker boshrelease which also comes with an errand for fetching the images. But I think this bosh-release could support both cases (PR's welcome). Also I agree on the TCP issue, however when using swarm there currently is no other way.

**Comment by drnic** [comment]
Closing. Moving the repo to the attic
